name: ClassIsland Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:

  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Build CIPX Package
      run: dotnet publish -c Release -p:CreateCipx=true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: CIPX Package
        path: cipx
